### ISSUE TITLE
Article on simple caching: a review/simplification?

### ISSUE THREAD

**Issue by crazy4groovy** [Xiphe/cachified#19]
Hi! I appreciate this lib, I think it has many useful applications!

I wondered about in terms of implementation, how much of it could be simplified? I wrote an article on a similar topic of TTL and LRU; perhaps you could review it and leave some comments? I'd love to hear your thoughts on what could be improved!

https://srjsdev.hashnode.dev/async-promise-cache-invalidation-strategies

Thanks, and Cheers!

**Comment by Xiphe** [comment]
Thanks for the feedback. I'm currently on vacation but will keep this on my list and have a look at it January 🤙

**Comment by Xiphe** [comment]
Had a glance on your article and it seems reasonable to me. Not sure what you mean with "how much of it could be simplified" in regards to this library though...

**Comment by Xiphe** [comment]
Closing since this is more of a discussion. Feel free to continue commenting here though.
