### ISSUE TITLE
Update the example in the docs to use a more "realistic" example

### ISSUE THREAD

**Issue by tomanagle** [Xiphe/cachified#32]
Just had a bit of confusion with the key, where it wasn't clear that it needs to be dynamic and was treated more like a namespace. It's probably not common but if someone does this it could lead to some really unexpected results.

For example, we want to cache a resource called `user` and the key was set to `user` instead of `user_${userId}`.

I'm happy to update the docs to either switch out the PI example or add another example.

Great library btw, going to keep us out of trouble :)

**Comment by Xiphe** [comment]
Hey @tomanagle you're right! that's a great idea! 
I was also thinking about using tables [like here](https://github.com/Xiphe/cachified/issues/16#issuecomment-1377047675) to better describe what's happening. 

If you'd like I'll happily accept a PR for this 👍
