### ISSUE TITLE
swv? Shouldn't it be swr?

### ISSUE THREAD

**Issue by kentcdodds** [Xiphe/cachified#6]
I noticed the metadata has `staleWhileRevalidate` shortened to `swv`. Shouldn't that be `swr`?

**Comment by Xiphe** [comment]
oh, you're right. Will fix this in a backwards-compatible way within the next days.

**Comment by Xiphe** [comment]
Fixed in [`3.0.0`](https://github.com/Xiphe/cachified/releases/tag/v3.0.0)

**Comment by kentcdodds** [comment]
Great! Thank you :)
